### ISSUE TITLE
Blank node creation error in deserializing JSON-LD

### ISSUE THREAD

**Issue by fils** [deiu/rdf2go#3] opened 2017-09-08 17:34 UTC
Reference: 
https://github.com/OpenCoreData/ocdGarden/blob/master/JSON-goLD/rdf2goTesting/main.go

Taking a JSON-LD document that contains blank nodes results in an error where all blank nodes get the same ID.

Expect something like

```
_:b0 <http://schema.org/description> "The Empire State Building is a 102-story landmark in New York City." .
_:b0 <http://schema.org/geo> _:b1 .
_:b0 <http://schema.org/image> <http://www.civil.usherbrooke.ca/cours/gci215a/empire-state-building.jpg> .
_:b0 <http://schema.org/name> "The Empire State Building" .
_:b1 <http://schema.org/latitude> "40.75"^^<http://www.w3.org/2001/XMLSchema#float> .
_:b1 <http://schema.org/longitude> "73.98"^^<http://www.w3.org/2001/XMLSchema#float> .
```

 Get

```
_:n0 <http://schema.org/description> "The Empire State Building is a 102-story landmark in New York City."^^<http://www.w3.org/2001/XMLSchema#string> .
_:n0 <http://schema.org/geo> _:n0 .
_:n0 <http://schema.org/image> <http://www.civil.usherbrooke.ca/cours/gci215a/empire-state-building.jpg> .
_:n0 <http://schema.org/name> "The Empire State Building"^^<http://www.w3.org/2001/XMLSchema#string> .
_:n0 <http://schema.org/latitude> "40.75"^^<http://www.w3.org/2001/XMLSchema#float> .
_:n0 <http://schema.org/longitude> "73.98"^^<http://www.w3.org/2001/XMLSchema#float> .
```	

Note the geo line at row 2 in both outputs.  
The rightmost blank node can not be _:n0 again.

Also, curious if I load multiple JSON-LD documents into a single graph if the blank nodes will be unique so that subsequent JSON-LD documents don't deserialize with conflicting blank node IDs.

**Comment by pebbe** [comment] 2021-07-10 13:23
A similar thing happens when parsing a turtle document

```go
package main

import (
	"github.com/deiu/rdf2go"

	"bytes"
	"fmt"
)

var (
	data = `
@prefix p: <http://localhost/> .

p:a1 p:b [ p:c "item1" ] .
p:a2 p:b [ p:c "item2" ] .
`
)

func main() {

	var buf bytes.Buffer
	buf.WriteString(data)

	baseUri := "http://localhost/"

	g := rdf2go.NewGraph(baseUri)

	// r is of type io.Reader
	g.Parse(&buf, "text/turtle")

	for tri := range g.IterTriples() {
		fmt.Println(tri)
	}
}
```

Output:

```
<http://localhost/a1> <http://localhost/b> _:n0 .
_:n0 <http://localhost/c> "item2" .
<http://localhost/a2> <http://localhost/b> _:n0 .
_:n0 <http://localhost/c> "item1" .
```

Expected output:

```
<http://localhost/a1> <http://localhost/b> _:n0 .
_:n1 <http://localhost/c> "item2" .
<http://localhost/a2> <http://localhost/b> _:n1 .
_:n0 <http://localhost/c> "item1" .

```

**Comment by cem-okulmus** [comment] 2023-04-06 14:19
So I need proper blanks for a project I am working. I checked the underlying parsing library, gon3, and there it produces proper distinct blanks. However, rdf2go uses strconv.Atoi to transform a string like "_:a7" into an integer, which of course throws an error and returns 0. Since the rdf2go doesn't check for the error, and just uses the integer as is, you only get 0s in blanks. 

Problematic line is here: https://github.com/deiu/rdf2go/blob/master/term.go#L226 
Not sure why rdf2go wants to convert blanks internally to integer, seems like a design choice that's begging for transformation errors like this. The easiest fix seems to me to just have the id of blanks stored as a string. I will address this in a private fork, could work on a merge request if desired, but as I said, my fix will involve changing the underlying struct of BlankNode.

**Comment by cem-okulmus** [comment] 2023-04-08 14:30
As an update, I now have a fixed version of rdf2go running locally. In addition to the bug I explained above, there is another issue with the gon3 library. 

As above, it's only a single line that needs to be updated: https://github.com/deiu/gon3/blob/f84eb1e0bd629a62676207d0a47516da8338cf60/parser.go#L485
Note the use of the fixed label "bnodeproplist" for _every occurence_ of blank property lists, so in triples notation that's every time we have something like  "s p1 [ p2 o1; p3 o2 ]". When creating a new blank, gon3 checks this label and if a mapping to that label exists, it just returns the existing blank node again. Thus, all blank property lists get the same blank id. Simply replacing the label with "" fixes this.

**Comment by deiu** [comment] 2023-04-08 20:28
Hi @cem-okulmus. Thank you for taking an interest to this library. I'm very busy currently but would love a PR with all the fixes you suggested above. All credit goes to you, of course. :)

**Comment by cem-okulmus** [comment] 2023-04-09 16:48
I created the PR  #9  here, and also one for github.com/deiu/gon3.  In addition to the fixes above, I also added .mod and .sum files, as it's not possible to build and test Go projects without them, at least not anymore.

**Comment by deiu** [comment] 2023-04-11 08:20
Thanks @cem-okulmus. I've merged your PRs. Please test again and close this issue if it's all good.

**Comment by cem-okulmus** [comment] 2023-04-11 09:03
I have now replaced my private repos with github.com/deiu/rdf2go and I can confirm that I can detect unique blanks. My current project requires distinct blanks to be able to extract certain properties from an RDF graph, so that serves as a suitable test case, I think. Of course, it might also make sense to write a proper test for this in rdf2go itself.

**Closed as completed** 2023-04-11 12:18 UTC
Labels: help wanted

**Comment by cem-okulmus** [comment] 2023-04-11 14:59
There is still another dumb problem, that I can see. The current go.mod that I added with the PR references the _old_ version of gon3. So the one that does not have the fix. Thus the problem is actually still there. I was a bit careless in my test this morning. Sorry about that. 
The fix is pretty simple, though, just need an updated go.mod file. Should I make another PR request?

**Comment by deiu** [comment] 2023-04-11 15:01
Yes please, I am currently travelling and only merge PRs. :(
